name: Shell Commands

on:
  push:
      branches:
        - master
jobs:
    app-hello-world:
        runs-on: ubuntu-latest
        steps:
          - name: pulling
            run: |
              git clone git@github:$GITHUB_REPOSITORY
              git checkout $GITHUB_SHA
          - name: testing
            run: ls -al
          - name: starting
            run: php test.php